/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Assignment } from "./Assignment";
import { AssignmentCountArgs } from "./AssignmentCountArgs";
import { AssignmentFindManyArgs } from "./AssignmentFindManyArgs";
import { AssignmentFindUniqueArgs } from "./AssignmentFindUniqueArgs";
import { CreateAssignmentArgs } from "./CreateAssignmentArgs";
import { UpdateAssignmentArgs } from "./UpdateAssignmentArgs";
import { DeleteAssignmentArgs } from "./DeleteAssignmentArgs";
import { Authority } from "../../authority/base/Authority";
import { Collector } from "../../collector/base/Collector";
import { Report } from "../../report/base/Report";
import { AssignmentService } from "../assignment.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Assignment)
export class AssignmentResolverBase {
  constructor(
    protected readonly service: AssignmentService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Assignment",
    action: "read",
    possession: "any",
  })
  async _assignmentsMeta(
    @graphql.Args() args: AssignmentCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Assignment])
  @nestAccessControl.UseRoles({
    resource: "Assignment",
    action: "read",
    possession: "any",
  })
  async assignments(
    @graphql.Args() args: AssignmentFindManyArgs
  ): Promise<Assignment[]> {
    return this.service.assignments(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Assignment, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Assignment",
    action: "read",
    possession: "own",
  })
  async assignment(
    @graphql.Args() args: AssignmentFindUniqueArgs
  ): Promise<Assignment | null> {
    const result = await this.service.assignment(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Assignment)
  @nestAccessControl.UseRoles({
    resource: "Assignment",
    action: "create",
    possession: "any",
  })
  async createAssignment(
    @graphql.Args() args: CreateAssignmentArgs
  ): Promise<Assignment> {
    return await this.service.createAssignment({
      ...args,
      data: {
        ...args.data,

        authority: args.data.authority
          ? {
              connect: args.data.authority,
            }
          : undefined,

        collector: args.data.collector
          ? {
              connect: args.data.collector,
            }
          : undefined,

        report: args.data.report
          ? {
              connect: args.data.report,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Assignment)
  @nestAccessControl.UseRoles({
    resource: "Assignment",
    action: "update",
    possession: "any",
  })
  async updateAssignment(
    @graphql.Args() args: UpdateAssignmentArgs
  ): Promise<Assignment | null> {
    try {
      return await this.service.updateAssignment({
        ...args,
        data: {
          ...args.data,

          authority: args.data.authority
            ? {
                connect: args.data.authority,
              }
            : undefined,

          collector: args.data.collector
            ? {
                connect: args.data.collector,
              }
            : undefined,

          report: args.data.report
            ? {
                connect: args.data.report,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Assignment)
  @nestAccessControl.UseRoles({
    resource: "Assignment",
    action: "delete",
    possession: "any",
  })
  async deleteAssignment(
    @graphql.Args() args: DeleteAssignmentArgs
  ): Promise<Assignment | null> {
    try {
      return await this.service.deleteAssignment(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Authority, {
    nullable: true,
    name: "authority",
  })
  @nestAccessControl.UseRoles({
    resource: "Authority",
    action: "read",
    possession: "any",
  })
  async getAuthority(
    @graphql.Parent() parent: Assignment
  ): Promise<Authority | null> {
    const result = await this.service.getAuthority(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Collector, {
    nullable: true,
    name: "collector",
  })
  @nestAccessControl.UseRoles({
    resource: "Collector",
    action: "read",
    possession: "any",
  })
  async getCollector(
    @graphql.Parent() parent: Assignment
  ): Promise<Collector | null> {
    const result = await this.service.getCollector(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Report, {
    nullable: true,
    name: "report",
  })
  @nestAccessControl.UseRoles({
    resource: "Report",
    action: "read",
    possession: "any",
  })
  async getReport(
    @graphql.Parent() parent: Assignment
  ): Promise<Report | null> {
    const result = await this.service.getReport(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
